### PR TITLE
Fix generated paths on Windows

### PR DESCRIPTION
**Pull request by phelioz**
Fixed generated paths on Windows. Have tested relative paths and seams to work okay unsure about absolute paths.
New to Rust lang so the code is probably hacky, just how I solved it.

### CODE REVIEW

**Comment by karroffel** [comment]
Thank you very much for the PR! It seems good to me, can you run `cargo fmt` and amend the changes to the commit?

**Comment by phelioz** [comment]
Sure, didn't know about cargo fmt. It's nice :)

**Comment by karroffel** [comment]
Thank you! Looks good to me!

Closes #5

**Comment by phelioz** [comment]
Happy to help!

**Pull request merged**
